// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: odpf/optimus/plugins/cli.proto

package optimus

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	optimus "github.com/odpf/optimus/api/proto/odpf/optimus"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginQuestion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string                        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Prompt       string                        `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Help         string                        `protobuf:"bytes,3,opt,name=help,proto3" json:"help,omitempty"`
	Default      string                        `protobuf:"bytes,4,opt,name=default,proto3" json:"default,omitempty"`
	Multiselect  []string                      `protobuf:"bytes,5,rep,name=multiselect,proto3" json:"multiselect,omitempty"`
	SubQuestions []*PluginQuestion_SubQuestion `protobuf:"bytes,6,rep,name=sub_questions,json=subQuestions,proto3" json:"sub_questions,omitempty"`
}

func (x *PluginQuestion) Reset() {
	*x = PluginQuestion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginQuestion) ProtoMessage() {}

func (x *PluginQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginQuestion.ProtoReflect.Descriptor instead.
func (*PluginQuestion) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_plugins_cli_proto_rawDescGZIP(), []int{0}
}

func (x *PluginQuestion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginQuestion) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *PluginQuestion) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

func (x *PluginQuestion) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *PluginQuestion) GetMultiselect() []string {
	if x != nil {
		return x.Multiselect
	}
	return nil
}

func (x *PluginQuestion) GetSubQuestions() []*PluginQuestion_SubQuestion {
	if x != nil {
		return x.SubQuestions
	}
	return nil
}

type PluginAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Question *PluginQuestion `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Value    string          `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PluginAnswer) Reset() {
	*x = PluginAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginAnswer) ProtoMessage() {}

func (x *PluginAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginAnswer.ProtoReflect.Descriptor instead.
func (*PluginAnswer) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_plugins_cli_proto_rawDescGZIP(), []int{1}
}

func (x *PluginAnswer) GetQuestion() *PluginQuestion {
	if x != nil {
		return x.Question
	}
	return nil
}

func (x *PluginAnswer) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetQuestions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetQuestions) Reset() {
	*x = GetQuestions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuestions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestions) ProtoMessage() {}

func (x *GetQuestions) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestions.ProtoReflect.Descriptor instead.
func (*GetQuestions) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_plugins_cli_proto_rawDescGZIP(), []int{2}
}

type ValidateQuestion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ValidateQuestion) Reset() {
	*x = ValidateQuestion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateQuestion) ProtoMessage() {}

func (x *ValidateQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateQuestion.ProtoReflect.Descriptor instead.
func (*ValidateQuestion) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_plugins_cli_proto_rawDescGZIP(), []int{3}
}

type Configs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Configs []*Configs_Config `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
}

func (x *Configs) Reset() {
	*x = Configs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Configs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configs) ProtoMessage() {}

func (x *Configs) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configs.ProtoReflect.Descriptor instead.
func (*Configs) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_plugins_cli_proto_rawDescGZIP(), []int{4}
}

func (x *Configs) GetConfigs() []*Configs_Config {
	if x != nil {
		return x.Configs
	}
	return nil
}

type DefaultConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DefaultConfig) Reset() {
	*x = DefaultConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultConfig) ProtoMessage() {}

func (x *DefaultConfig) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultConfig.ProtoReflect.Descriptor instead.
func (*DefaultConfig) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_plugins_cli_proto_rawDescGZIP(), []int{5}
}

type Assets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Assets []*Assets_Asset `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
}

func (x *Assets) Reset() {
	*x = Assets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Assets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assets) ProtoMessage() {}

func (x *Assets) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assets.ProtoReflect.Descriptor instead.
func (*Assets) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_plugins_cli_proto_rawDescGZIP(), []int{6}
}

func (x *Assets) GetAssets() []*Assets_Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type DefaultAssets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DefaultAssets) Reset() {
	*x = DefaultAssets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultAssets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultAssets) ProtoMessage() {}

func (x *DefaultAssets) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultAssets.ProtoReflect.Descriptor instead.
func (*DefaultAssets) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_plugins_cli_proto_rawDescGZIP(), []int{7}
}

type CompileAssets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CompileAssets) Reset() {
	*x = CompileAssets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompileAssets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileAssets) ProtoMessage() {}

func (x *CompileAssets) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileAssets.ProtoReflect.Descriptor instead.
func (*CompileAssets) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_plugins_cli_proto_rawDescGZIP(), []int{8}
}

type PluginQuestion_SubQuestion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IfValue   string            `protobuf:"bytes,1,opt,name=if_value,json=ifValue,proto3" json:"if_value,omitempty"`
	Questions []*PluginQuestion `protobuf:"bytes,2,rep,name=questions,proto3" json:"questions,omitempty"`
}

func (x *PluginQuestion_SubQuestion) Reset() {
	*x = PluginQuestion_SubQuestion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginQuestion_SubQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginQuestion_SubQuestion) ProtoMessage() {}

func (x *PluginQuestion_SubQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginQuestion_SubQuestion.ProtoReflect.Descriptor instead.
func (*PluginQuestion_SubQuestion) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_plugins_cli_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PluginQuestion_SubQuestion) GetIfValue() string {
	if x != nil {
		return x.IfValue
	}
	return ""
}

func (x *PluginQuestion_SubQuestion) GetQuestions() []*PluginQuestion {
	if x != nil {
		return x.Questions
	}
	return nil
}

type GetQuestions_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobName string         `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	Options *PluginOptions `protobuf:"bytes,40,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *GetQuestions_Request) Reset() {
	*x = GetQuestions_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuestions_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestions_Request) ProtoMessage() {}

func (x *GetQuestions_Request) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestions_Request.ProtoReflect.Descriptor instead.
func (*GetQuestions_Request) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_plugins_cli_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GetQuestions_Request) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *GetQuestions_Request) GetOptions() *PluginOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type GetQuestions_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Questions []*PluginQuestion `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
}

func (x *GetQuestions_Response) Reset() {
	*x = GetQuestions_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuestions_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestions_Response) ProtoMessage() {}

func (x *GetQuestions_Response) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestions_Response.ProtoReflect.Descriptor instead.
func (*GetQuestions_Response) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_plugins_cli_proto_rawDescGZIP(), []int{2, 1}
}

func (x *GetQuestions_Response) GetQuestions() []*PluginQuestion {
	if x != nil {
		return x.Questions
	}
	return nil
}

type ValidateQuestion_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer  *PluginAnswer  `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	Options *PluginOptions `protobuf:"bytes,40,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *ValidateQuestion_Request) Reset() {
	*x = ValidateQuestion_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateQuestion_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateQuestion_Request) ProtoMessage() {}

func (x *ValidateQuestion_Request) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateQuestion_Request.ProtoReflect.Descriptor instead.
func (*ValidateQuestion_Request) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_plugins_cli_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ValidateQuestion_Request) GetAnswer() *PluginAnswer {
	if x != nil {
		return x.Answer
	}
	return nil
}

func (x *ValidateQuestion_Request) GetOptions() *PluginOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ValidateQuestion_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ValidateQuestion_Response) Reset() {
	*x = ValidateQuestion_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateQuestion_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateQuestion_Response) ProtoMessage() {}

func (x *ValidateQuestion_Response) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateQuestion_Response.ProtoReflect.Descriptor instead.
func (*ValidateQuestion_Response) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_plugins_cli_proto_rawDescGZIP(), []int{3, 1}
}

func (x *ValidateQuestion_Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ValidateQuestion_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Configs_Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Configs_Config) Reset() {
	*x = Configs_Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Configs_Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configs_Config) ProtoMessage() {}

func (x *Configs_Config) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configs_Config.ProtoReflect.Descriptor instead.
func (*Configs_Config) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_plugins_cli_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Configs_Config) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Configs_Config) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DefaultConfig_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answers       []*PluginAnswer `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
	ParentConfigs *Configs        `protobuf:"bytes,2,opt,name=parent_configs,json=parentConfigs,proto3" json:"parent_configs,omitempty"`
	Options       *PluginOptions  `protobuf:"bytes,40,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *DefaultConfig_Request) Reset() {
	*x = DefaultConfig_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultConfig_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultConfig_Request) ProtoMessage() {}

func (x *DefaultConfig_Request) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultConfig_Request.ProtoReflect.Descriptor instead.
func (*DefaultConfig_Request) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_plugins_cli_proto_rawDescGZIP(), []int{5, 0}
}

func (x *DefaultConfig_Request) GetAnswers() []*PluginAnswer {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *DefaultConfig_Request) GetParentConfigs() *Configs {
	if x != nil {
		return x.ParentConfigs
	}
	return nil
}

func (x *DefaultConfig_Request) GetOptions() *PluginOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type DefaultConfig_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *Configs `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *DefaultConfig_Response) Reset() {
	*x = DefaultConfig_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultConfig_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultConfig_Response) ProtoMessage() {}

func (x *DefaultConfig_Response) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultConfig_Response.ProtoReflect.Descriptor instead.
func (*DefaultConfig_Response) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_plugins_cli_proto_rawDescGZIP(), []int{5, 1}
}

func (x *DefaultConfig_Response) GetConfig() *Configs {
	if x != nil {
		return x.Config
	}
	return nil
}

type Assets_Asset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Assets_Asset) Reset() {
	*x = Assets_Asset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Assets_Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assets_Asset) ProtoMessage() {}

func (x *Assets_Asset) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assets_Asset.ProtoReflect.Descriptor instead.
func (*Assets_Asset) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_plugins_cli_proto_rawDescGZIP(), []int{6, 0}
}

func (x *Assets_Asset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Assets_Asset) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DefaultAssets_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answers       []*PluginAnswer `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
	ParentConfigs *Configs        `protobuf:"bytes,2,opt,name=parent_configs,json=parentConfigs,proto3" json:"parent_configs,omitempty"`
	Options       *PluginOptions  `protobuf:"bytes,40,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *DefaultAssets_Request) Reset() {
	*x = DefaultAssets_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultAssets_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultAssets_Request) ProtoMessage() {}

func (x *DefaultAssets_Request) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultAssets_Request.ProtoReflect.Descriptor instead.
func (*DefaultAssets_Request) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_plugins_cli_proto_rawDescGZIP(), []int{7, 0}
}

func (x *DefaultAssets_Request) GetAnswers() []*PluginAnswer {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *DefaultAssets_Request) GetParentConfigs() *Configs {
	if x != nil {
		return x.ParentConfigs
	}
	return nil
}

func (x *DefaultAssets_Request) GetOptions() *PluginOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type DefaultAssets_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Assets *Assets `protobuf:"bytes,1,opt,name=assets,proto3" json:"assets,omitempty"`
}

func (x *DefaultAssets_Response) Reset() {
	*x = DefaultAssets_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultAssets_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultAssets_Response) ProtoMessage() {}

func (x *DefaultAssets_Response) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultAssets_Response.ProtoReflect.Descriptor instead.
func (*DefaultAssets_Response) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_plugins_cli_proto_rawDescGZIP(), []int{7, 1}
}

func (x *DefaultAssets_Response) GetAssets() *Assets {
	if x != nil {
		return x.Assets
	}
	return nil
}

type CompileAssets_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Configs          *Configs                    `protobuf:"bytes,1,opt,name=configs,proto3" json:"configs,omitempty"`
	Assets           *Assets                     `protobuf:"bytes,2,opt,name=assets,proto3" json:"assets,omitempty"`
	Window           *optimus.TaskWindow         `protobuf:"bytes,3,opt,name=window,proto3" json:"window,omitempty"`
	InstanceSchedule *timestamp.Timestamp        `protobuf:"bytes,4,opt,name=instance_schedule,json=instanceSchedule,proto3" json:"instance_schedule,omitempty"`
	InstanceData     []*optimus.InstanceSpecData `protobuf:"bytes,5,rep,name=instance_data,json=instanceData,proto3" json:"instance_data,omitempty"`
	Options          *PluginOptions              `protobuf:"bytes,40,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *CompileAssets_Request) Reset() {
	*x = CompileAssets_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompileAssets_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileAssets_Request) ProtoMessage() {}

func (x *CompileAssets_Request) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileAssets_Request.ProtoReflect.Descriptor instead.
func (*CompileAssets_Request) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_plugins_cli_proto_rawDescGZIP(), []int{8, 0}
}

func (x *CompileAssets_Request) GetConfigs() *Configs {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *CompileAssets_Request) GetAssets() *Assets {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *CompileAssets_Request) GetWindow() *optimus.TaskWindow {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *CompileAssets_Request) GetInstanceSchedule() *timestamp.Timestamp {
	if x != nil {
		return x.InstanceSchedule
	}
	return nil
}

func (x *CompileAssets_Request) GetInstanceData() []*optimus.InstanceSpecData {
	if x != nil {
		return x.InstanceData
	}
	return nil
}

func (x *CompileAssets_Request) GetOptions() *PluginOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type CompileAssets_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Assets *Assets `protobuf:"bytes,1,opt,name=assets,proto3" json:"assets,omitempty"`
}

func (x *CompileAssets_Response) Reset() {
	*x = CompileAssets_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompileAssets_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileAssets_Response) ProtoMessage() {}

func (x *CompileAssets_Response) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_optimus_plugins_cli_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileAssets_Response.ProtoReflect.Descriptor instead.
func (*CompileAssets_Response) Descriptor() ([]byte, []int) {
	return file_odpf_optimus_plugins_cli_proto_rawDescGZIP(), []int{8, 1}
}

func (x *CompileAssets_Response) GetAssets() *Assets {
	if x != nil {
		return x.Assets
	}
	return nil
}

var File_odpf_optimus_plugins_cli_proto protoreflect.FileDescriptor

var file_odpf_optimus_plugins_cli_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6f, 0x64, 0x70, 0x66, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2f, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2f, 0x63, 0x6c, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x14, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x6f, 0x64, 0x70, 0x66, 0x2f, 0x6f, 0x70,
	0x74, 0x69, 0x6d, 0x75, 0x73, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2f, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x22, 0x6f, 0x64, 0x70, 0x66, 0x2f, 0x6f,
	0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd1, 0x02, 0x0a,
	0x0e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x65, 0x6c, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x65, 0x6c, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x75, 0x6c,
	0x74, 0x69, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b,
	0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x12, 0x55, 0x0a, 0x0d, 0x73,
	0x75, 0x62, 0x5f, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x30, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75,
	0x73, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x75, 0x62, 0x51, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x73, 0x75, 0x62, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x1a, 0x6c, 0x0a, 0x0b, 0x53, 0x75, 0x62, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x66, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x66, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x42, 0x0a, 0x09,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x24, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x22, 0x66, 0x0a, 0x0c, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x12, 0x40, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75,
	0x73, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xc3, 0x01, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x63, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6a, 0x6f, 0x62, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x3d, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x28, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x4e,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x09, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x51, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x09, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xd5,
	0x01, 0x0a, 0x10, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x1a, 0x84, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x3a, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x3d, 0x0a, 0x07, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x28, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6f,
	0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x3a, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x7d, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x73, 0x12, 0x3e, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75,
	0x73, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x73, 0x1a, 0x32, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xa1, 0x02, 0x0a, 0x0d, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0xcc, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69,
	0x6d, 0x75, 0x73, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x73, 0x12, 0x44, 0x0a, 0x0e, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x64, 0x70, 0x66,
	0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73,
	0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x52, 0x0d, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x12, 0x3d, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x28, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e,
	0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e,
	0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x41, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75,
	0x73, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x73, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x77, 0x0a, 0x06, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x73, 0x12, 0x3a, 0x0a, 0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d,
	0x75, 0x73, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x73, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x1a,
	0x31, 0x0a, 0x05, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0xa0, 0x02, 0x0a, 0x0d, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x73, 0x1a, 0xcc, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x3c, 0x0a, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73,
	0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x12, 0x44,
	0x0a, 0x0e, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70,
	0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x73, 0x52, 0x0d, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x73, 0x12, 0x3d, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x28, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74,
	0x69, 0x6d, 0x75, 0x73, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x1a, 0x40, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x34, 0x0a, 0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x52, 0x06, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x73, 0x22, 0xcb, 0x03, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c,
	0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x1a, 0xf7, 0x02, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69,
	0x6d, 0x75, 0x73, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x73, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x12, 0x34, 0x0a, 0x06,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f,
	0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x73, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x52, 0x06, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x73, 0x12, 0x30, 0x0a, 0x06, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75,
	0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x52, 0x06, 0x77, 0x69,
	0x6e, 0x64, 0x6f, 0x77, 0x12, 0x47, 0x0a, 0x11, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x5f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x10, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x43, 0x0a,
	0x0d, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69,
	0x6d, 0x75, 0x73, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x70, 0x65, 0x63,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x3d, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x28, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d,
	0x75, 0x73, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x1a, 0x40, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a,
	0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x73, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x52, 0x06, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x73, 0x32, 0xa7, 0x04, 0x0a, 0x03, 0x43, 0x4c, 0x49, 0x12, 0x67, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2a, 0x2e, 0x6f, 0x64,
	0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f,
	0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x47,
	0x65, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x73, 0x0a, 0x10, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e,
	0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e,
	0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6a, 0x0a, 0x0d, 0x44, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x2b, 0x2e, 0x6f, 0x64, 0x70,
	0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x73, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f,
	0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x44,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6a, 0x0a, 0x0d, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x12, 0x2b, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70,
	0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x44, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d,
	0x75, 0x73, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x6a, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x73, 0x12, 0x2b, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75,
	0x73, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c,
	0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2c, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x4c, 0x0a,
	0x1e, 0x69, 0x6f, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x2e,
	0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x42,
	0x08, 0x43, 0x4c, 0x49, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1e, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x64, 0x70, 0x66, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x6e, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_odpf_optimus_plugins_cli_proto_rawDescOnce sync.Once
	file_odpf_optimus_plugins_cli_proto_rawDescData = file_odpf_optimus_plugins_cli_proto_rawDesc
)

func file_odpf_optimus_plugins_cli_proto_rawDescGZIP() []byte {
	file_odpf_optimus_plugins_cli_proto_rawDescOnce.Do(func() {
		file_odpf_optimus_plugins_cli_proto_rawDescData = protoimpl.X.CompressGZIP(file_odpf_optimus_plugins_cli_proto_rawDescData)
	})
	return file_odpf_optimus_plugins_cli_proto_rawDescData
}

var file_odpf_optimus_plugins_cli_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_odpf_optimus_plugins_cli_proto_goTypes = []interface{}{
	(*PluginQuestion)(nil),             // 0: odpf.optimus.plugins.PluginQuestion
	(*PluginAnswer)(nil),               // 1: odpf.optimus.plugins.PluginAnswer
	(*GetQuestions)(nil),               // 2: odpf.optimus.plugins.GetQuestions
	(*ValidateQuestion)(nil),           // 3: odpf.optimus.plugins.ValidateQuestion
	(*Configs)(nil),                    // 4: odpf.optimus.plugins.Configs
	(*DefaultConfig)(nil),              // 5: odpf.optimus.plugins.DefaultConfig
	(*Assets)(nil),                     // 6: odpf.optimus.plugins.Assets
	(*DefaultAssets)(nil),              // 7: odpf.optimus.plugins.DefaultAssets
	(*CompileAssets)(nil),              // 8: odpf.optimus.plugins.CompileAssets
	(*PluginQuestion_SubQuestion)(nil), // 9: odpf.optimus.plugins.PluginQuestion.SubQuestion
	(*GetQuestions_Request)(nil),       // 10: odpf.optimus.plugins.GetQuestions.Request
	(*GetQuestions_Response)(nil),      // 11: odpf.optimus.plugins.GetQuestions.Response
	(*ValidateQuestion_Request)(nil),   // 12: odpf.optimus.plugins.ValidateQuestion.Request
	(*ValidateQuestion_Response)(nil),  // 13: odpf.optimus.plugins.ValidateQuestion.Response
	(*Configs_Config)(nil),             // 14: odpf.optimus.plugins.Configs.Config
	(*DefaultConfig_Request)(nil),      // 15: odpf.optimus.plugins.DefaultConfig.Request
	(*DefaultConfig_Response)(nil),     // 16: odpf.optimus.plugins.DefaultConfig.Response
	(*Assets_Asset)(nil),               // 17: odpf.optimus.plugins.Assets.Asset
	(*DefaultAssets_Request)(nil),      // 18: odpf.optimus.plugins.DefaultAssets.Request
	(*DefaultAssets_Response)(nil),     // 19: odpf.optimus.plugins.DefaultAssets.Response
	(*CompileAssets_Request)(nil),      // 20: odpf.optimus.plugins.CompileAssets.Request
	(*CompileAssets_Response)(nil),     // 21: odpf.optimus.plugins.CompileAssets.Response
	(*PluginOptions)(nil),              // 22: odpf.optimus.plugins.PluginOptions
	(*optimus.TaskWindow)(nil),         // 23: odpf.optimus.TaskWindow
	(*timestamp.Timestamp)(nil),        // 24: google.protobuf.Timestamp
	(*optimus.InstanceSpecData)(nil),   // 25: odpf.optimus.InstanceSpecData
}
var file_odpf_optimus_plugins_cli_proto_depIdxs = []int32{
	9,  // 0: odpf.optimus.plugins.PluginQuestion.sub_questions:type_name -> odpf.optimus.plugins.PluginQuestion.SubQuestion
	0,  // 1: odpf.optimus.plugins.PluginAnswer.question:type_name -> odpf.optimus.plugins.PluginQuestion
	14, // 2: odpf.optimus.plugins.Configs.configs:type_name -> odpf.optimus.plugins.Configs.Config
	17, // 3: odpf.optimus.plugins.Assets.assets:type_name -> odpf.optimus.plugins.Assets.Asset
	0,  // 4: odpf.optimus.plugins.PluginQuestion.SubQuestion.questions:type_name -> odpf.optimus.plugins.PluginQuestion
	22, // 5: odpf.optimus.plugins.GetQuestions.Request.options:type_name -> odpf.optimus.plugins.PluginOptions
	0,  // 6: odpf.optimus.plugins.GetQuestions.Response.questions:type_name -> odpf.optimus.plugins.PluginQuestion
	1,  // 7: odpf.optimus.plugins.ValidateQuestion.Request.answer:type_name -> odpf.optimus.plugins.PluginAnswer
	22, // 8: odpf.optimus.plugins.ValidateQuestion.Request.options:type_name -> odpf.optimus.plugins.PluginOptions
	1,  // 9: odpf.optimus.plugins.DefaultConfig.Request.answers:type_name -> odpf.optimus.plugins.PluginAnswer
	4,  // 10: odpf.optimus.plugins.DefaultConfig.Request.parent_configs:type_name -> odpf.optimus.plugins.Configs
	22, // 11: odpf.optimus.plugins.DefaultConfig.Request.options:type_name -> odpf.optimus.plugins.PluginOptions
	4,  // 12: odpf.optimus.plugins.DefaultConfig.Response.config:type_name -> odpf.optimus.plugins.Configs
	1,  // 13: odpf.optimus.plugins.DefaultAssets.Request.answers:type_name -> odpf.optimus.plugins.PluginAnswer
	4,  // 14: odpf.optimus.plugins.DefaultAssets.Request.parent_configs:type_name -> odpf.optimus.plugins.Configs
	22, // 15: odpf.optimus.plugins.DefaultAssets.Request.options:type_name -> odpf.optimus.plugins.PluginOptions
	6,  // 16: odpf.optimus.plugins.DefaultAssets.Response.assets:type_name -> odpf.optimus.plugins.Assets
	4,  // 17: odpf.optimus.plugins.CompileAssets.Request.configs:type_name -> odpf.optimus.plugins.Configs
	6,  // 18: odpf.optimus.plugins.CompileAssets.Request.assets:type_name -> odpf.optimus.plugins.Assets
	23, // 19: odpf.optimus.plugins.CompileAssets.Request.window:type_name -> odpf.optimus.TaskWindow
	24, // 20: odpf.optimus.plugins.CompileAssets.Request.instance_schedule:type_name -> google.protobuf.Timestamp
	25, // 21: odpf.optimus.plugins.CompileAssets.Request.instance_data:type_name -> odpf.optimus.InstanceSpecData
	22, // 22: odpf.optimus.plugins.CompileAssets.Request.options:type_name -> odpf.optimus.plugins.PluginOptions
	6,  // 23: odpf.optimus.plugins.CompileAssets.Response.assets:type_name -> odpf.optimus.plugins.Assets
	10, // 24: odpf.optimus.plugins.CLI.GetQuestions:input_type -> odpf.optimus.plugins.GetQuestions.Request
	12, // 25: odpf.optimus.plugins.CLI.ValidateQuestion:input_type -> odpf.optimus.plugins.ValidateQuestion.Request
	15, // 26: odpf.optimus.plugins.CLI.DefaultConfig:input_type -> odpf.optimus.plugins.DefaultConfig.Request
	18, // 27: odpf.optimus.plugins.CLI.DefaultAssets:input_type -> odpf.optimus.plugins.DefaultAssets.Request
	20, // 28: odpf.optimus.plugins.CLI.CompileAssets:input_type -> odpf.optimus.plugins.CompileAssets.Request
	11, // 29: odpf.optimus.plugins.CLI.GetQuestions:output_type -> odpf.optimus.plugins.GetQuestions.Response
	13, // 30: odpf.optimus.plugins.CLI.ValidateQuestion:output_type -> odpf.optimus.plugins.ValidateQuestion.Response
	16, // 31: odpf.optimus.plugins.CLI.DefaultConfig:output_type -> odpf.optimus.plugins.DefaultConfig.Response
	19, // 32: odpf.optimus.plugins.CLI.DefaultAssets:output_type -> odpf.optimus.plugins.DefaultAssets.Response
	21, // 33: odpf.optimus.plugins.CLI.CompileAssets:output_type -> odpf.optimus.plugins.CompileAssets.Response
	29, // [29:34] is the sub-list for method output_type
	24, // [24:29] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_odpf_optimus_plugins_cli_proto_init() }
func file_odpf_optimus_plugins_cli_proto_init() {
	if File_odpf_optimus_plugins_cli_proto != nil {
		return
	}
	file_odpf_optimus_plugins_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_odpf_optimus_plugins_cli_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginQuestion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_plugins_cli_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_plugins_cli_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuestions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_plugins_cli_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateQuestion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_plugins_cli_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Configs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_plugins_cli_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_plugins_cli_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Assets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_plugins_cli_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultAssets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_plugins_cli_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompileAssets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_plugins_cli_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginQuestion_SubQuestion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_plugins_cli_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuestions_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_plugins_cli_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuestions_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_plugins_cli_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateQuestion_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_plugins_cli_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateQuestion_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_plugins_cli_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Configs_Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_plugins_cli_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultConfig_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_plugins_cli_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultConfig_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_plugins_cli_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Assets_Asset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_plugins_cli_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultAssets_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_plugins_cli_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultAssets_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_plugins_cli_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompileAssets_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_optimus_plugins_cli_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompileAssets_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_odpf_optimus_plugins_cli_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_odpf_optimus_plugins_cli_proto_goTypes,
		DependencyIndexes: file_odpf_optimus_plugins_cli_proto_depIdxs,
		MessageInfos:      file_odpf_optimus_plugins_cli_proto_msgTypes,
	}.Build()
	File_odpf_optimus_plugins_cli_proto = out.File
	file_odpf_optimus_plugins_cli_proto_rawDesc = nil
	file_odpf_optimus_plugins_cli_proto_goTypes = nil
	file_odpf_optimus_plugins_cli_proto_depIdxs = nil
}
