// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package optimus

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TaskClient is the client API for Task service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskClient interface {
	// GenerateDestination derive destination from config and assets
	GenerateDestination(ctx context.Context, in *GenerateDestination_Request, opts ...grpc.CallOption) (*GenerateDestination_Response, error)
	// GenerateDependencies return names of job destination on which this unit
	// is dependent on
	GenerateDependencies(ctx context.Context, in *GenerateDependencies_Request, opts ...grpc.CallOption) (*GenerateDependencies_Response, error)
}

type taskClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskClient(cc grpc.ClientConnInterface) TaskClient {
	return &taskClient{cc}
}

func (c *taskClient) GenerateDestination(ctx context.Context, in *GenerateDestination_Request, opts ...grpc.CallOption) (*GenerateDestination_Response, error) {
	out := new(GenerateDestination_Response)
	err := c.cc.Invoke(ctx, "/odpf.optimus.plugins.Task/GenerateDestination", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskClient) GenerateDependencies(ctx context.Context, in *GenerateDependencies_Request, opts ...grpc.CallOption) (*GenerateDependencies_Response, error) {
	out := new(GenerateDependencies_Response)
	err := c.cc.Invoke(ctx, "/odpf.optimus.plugins.Task/GenerateDependencies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServer is the server API for Task service.
// All implementations must embed UnimplementedTaskServer
// for forward compatibility
type TaskServer interface {
	// GenerateDestination derive destination from config and assets
	GenerateDestination(context.Context, *GenerateDestination_Request) (*GenerateDestination_Response, error)
	// GenerateDependencies return names of job destination on which this unit
	// is dependent on
	GenerateDependencies(context.Context, *GenerateDependencies_Request) (*GenerateDependencies_Response, error)
	mustEmbedUnimplementedTaskServer()
}

// UnimplementedTaskServer must be embedded to have forward compatible implementations.
type UnimplementedTaskServer struct {
}

func (UnimplementedTaskServer) GenerateDestination(context.Context, *GenerateDestination_Request) (*GenerateDestination_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateDestination not implemented")
}
func (UnimplementedTaskServer) GenerateDependencies(context.Context, *GenerateDependencies_Request) (*GenerateDependencies_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateDependencies not implemented")
}
func (UnimplementedTaskServer) mustEmbedUnimplementedTaskServer() {}

// UnsafeTaskServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServer will
// result in compilation errors.
type UnsafeTaskServer interface {
	mustEmbedUnimplementedTaskServer()
}

func RegisterTaskServer(s grpc.ServiceRegistrar, srv TaskServer) {
	s.RegisterService(&Task_ServiceDesc, srv)
}

func _Task_GenerateDestination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateDestination_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).GenerateDestination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/odpf.optimus.plugins.Task/GenerateDestination",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).GenerateDestination(ctx, req.(*GenerateDestination_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Task_GenerateDependencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateDependencies_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).GenerateDependencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/odpf.optimus.plugins.Task/GenerateDependencies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).GenerateDependencies(ctx, req.(*GenerateDependencies_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Task_ServiceDesc is the grpc.ServiceDesc for Task service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Task_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "odpf.optimus.plugins.Task",
	HandlerType: (*TaskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateDestination",
			Handler:    _Task_GenerateDestination_Handler,
		},
		{
			MethodName: "GenerateDependencies",
			Handler:    _Task_GenerateDependencies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "odpf/optimus/plugins/task.proto",
}
